[hpp-python]
url = "github:humanoid-path-planner"

[hpp-toppra]
src_deps = ["hpp-python", "toppra"]
url = "."

[toppra]
apt_deps = ["python3-pybind11"]
configure_args = ["-S", "cpp"]
url = "github:hungpham2511"
version = "0.6.8"
