<?xml version='1.0'?>
<package format='3'>
  <name>hpp_toppra</name>
  <version>9.0.2</version>
  <description>Bridge between HPP and TOPPRA</description>
  <author>Joseph Mirabel</author>
  <author>Florent Lamiraux</author>
  <author>Paul Sardin</author>
  <maintainer email='guilhem.saurel@laas.fr'>Guilhem Saurel</maintainer>
  <license>LGPL</license>
  <url type='website'>https://github.com/jmirabel/hpp-toppra</url>

  <depend>hpp_python</depend>
  <depend>toppra</depend>

  <test_depend>catch2</test_depend>

  <buildtool_depend>cmake</buildtool_depend>
  <build_depend>jrl_cmakemodules</build_depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
